spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trainings
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  liquibase:
    enabled: true